#choices correspond to questions.keys()
choices = [
        ["A. 22","B. 28","C. 34","D. 41"],
        ["A. Demonic Reaper","B. The Evil Supard","C. Dead End","D. Protector of Children", "E. Guard Dog Ruijerd"],
        ["A. Demon","B. Beastfolk","C. Marewolf","D. Forestor"],
        ["A. 18","B. 28","C. 37","D. 128"],
        ["A. during their childhood","B. during Paul's adventuring days","C. after Paul married Zenith","D. shortly before Rudeus was born"],
        ["A. human","B. demon","C. half-elf","D. half-elf, quarter human and quarter beastfolk", "E. half-beastfolk, half-demon"],
        ["A. True","B. False"],
        ["A. Intermediate","B. Advanced", "C. Saint", "D. King", "E. Emperor"],
        ["A. Water God Style, Sword God Style, North God Style","B. Fire Style, Sword Style, Water Style", "C. Sword God Style, Dragon God Style, Demon God Style"],
        ["A. 1st","B. 3rd","C. 4th","D. 7th"],
        ["A. Asura Kingdom","B. Holy Milis Kingdom","C. Kingdom of the Dragon King","D. Three Magic Nation Alliance "],  
        ["A. Beastfolk, Monsters, Gods","B. Elves Race, Dwarfs Race and Beastfolk","C. Seafolk, Sky Race (Angles) and Beastfolk"],
        ["A. Notos","B. Boreas","C. Euros", "D. Zephyrus", "E. (No Middle Name)"],
        ["A. True","B. False"],
        ["A. Dragon God Orsted","B. Sword God, Gal Farion", "C. Nanahoshi Shizuka (Silent Seven Stars)", "D. Saint Milis", "E. Ars, the Hero of Humanity"],
        ["A. Aish and Julie","B. Aisha and Norn","C. Lilia and Zenith", "D. Lucy and Lara"],
        ["A. 100","B. 10","C. 1","D. 0.01"],
        ["A. Aiding the First Dragon God's destruction of all 6 other worlds.","B. Achieving true bankai at the age of 3","C. Defeating Demon God Laplace during the Third Great Human-Demon War","D. Opening a restaurant that made deep fried chicken"],
        ["A. Central Continent","B. Begaritt Continent","C. Heaven Continent","D. Demon Continent"],
        ["A. Because of the teleportation traps of course !","B. Because of the 9-headed hydra deep within its depths","C. Because of the bloodthirsty monsters inside it","D. Because of the nearby empire of human-sized ants, numbering in the thousands"],
        ["A. A term to describe a particular formation of monsters, often used by adventurers.","B. The term used to describe Advanced-rank swordsmen who aspire to rise to the Saint-rank.","C. A region full of conflicting nations within the Central Continent.","D. A region full of conflicting Demon Lords in the Demon Continent."],
        ["A. a famous healer","B. a school teacher","C. a poor farm girl","D. a noble lady"],
        ["A. the strongest metal in the Demon Continent, Bofadeez","B. the hide of their first hunted dragon","C. their tails","D. their own ancestors, passed down through history"],
        ["A. True","B. False"],
        ["A. Fang of the Black Wolves...S","B. Paul's Merry Adventurers...A","C. Fittoa Search and Rescue...A","D. Steppe Ladder...S"],
        ["A. Mad Dog","B. Mad Sword King","C. The Forest Goddess","D. Black Fang Sword King"],
        ["A. Ars, the Hero of Humanity","B. Fighting God ||Alderaan(?)|| ","C. Demon God Laplace","D. Kishirika Kishirisu, the Great Demon Empress"],
        ["A. Kishirika Kishirisu, the Great Demon Empress","B. Dragon God ||Laplace|| ","C. Fighting God ||Alderaan(?)||","D. Technique God Laplace"],
        ["A. Armoured Dragon King, Perugius","B. Kishirika Kishirisu, the Great Demon Empress ","C. Demon God Laplace"],
        ["A. North God Kalmon I","B. North God Kalmon III","C. Fire Emperor Feroze Star", "D. Dragon God Urupen", "E. Gaunis Freean Asura, the Queen of Asura"],
        ["A. Armoured Dragon King, Perugius","B. North God Kalmon I","C. Ruijerd Superdia", "D. Fire Emperor Feroze Star"],
        ["A. Kenya Boreas Greyrat","B. Hilda Boreas Greyrat","C. Philip Boreas Greyrat","D. Sauros Boreas Greyrat"],
        ["A. the grandson of the current Pope of Holy Milis Kingdom","B. the chosen hero, destined to save the world","C. a soyboy","D. the world's strongest adventurer"],
        ["A. first Dragon God","B. 100th-generation Dragon God","C. strongest Dragon God","D. weakest Dragon God"],
        ["A. Enter the Heaven Continent, and from there descend towards the northen area of the Central Continent\n","B. Cross the wide ocean after leaving Wind port, reaching the Asuran capital within 3~6 months.\n","C. Make use of ancient Teleportation Formations scattered throughout the Demon Continent, reaching the Central Continent in around 10~15 minutes.\n","D. Leave the Demon Continent via Wind port, and from there, enter Milis Continent. Then, travel  across the entirety of Milis continent to West port, finally reaching East Port after another voyage."],
        ["A. Earth","B. Mushoku Tensei","C. The Six-Faced World","D. The Human World (人の世界)", "E. (Unamed)"],
        ["A. Monkey","B. Human","C. Beast","D. Demon", "E. Sky"],
        ["A. Inventing unique culinary delights and recipes","B. Causing the Teleportation Incident","C. Being Orsted's lover"],
        ["A. Dragon Touki","B. Summoning Magic","C. Dragon Gate", "D. Sealing Magic"],
        ["A. Blessing of Youth","B. Earth Magic","C. Great Strength", "D. Unparelled Insight"],
        ["A. To protect the Beast folk from all harm","B. To destroy the Demon God Laplace","C. To join the chosen one's side, aiding them in saving the world.", "D. So that people from all over the land may satisfy their cuddle tendencies"],
        ["A. The Cathedral Knights","B. The Missionary Knights","C. The Temple Knights"],
        ["A. Eyes of Destruction","B. Eyes of Magical Power","C. Eyes of Identification", "D. Eyes of Distant Sight"],
        ["A. Eyes of X-ray Vision","B. Eyes of Foresight","C. Eyes of Absorption", "D. Eyes of Mana Disruption"],
        ["A. Eyes of Distant Sight","B. Eyes of Foresight","C. Eyes of Magical Power", "D. Eyes of X-ray Vision"],
      
      
              ]