#question bank
questions = {
      'At what age was Rudeus hit by a truck during his previous life ?': 'C', 
      'Ruijerd Superdia is also known as... ?': ['C','E'],
      'Ghyslaine is part of the ___ race.': 'B',
      'How old was Roxy when she first met Rudeus ?': 'C',
      'Lilia first met Paul...': 'A',
      'Sylphy is a(n)...? ': ['C','D'],
      'Ruijerd Superdia had lived through and served in all 4 Human-Demon Wars throughout time. ': 'B',
      'Rudeus could use ___-ranked water magic at the age of 5.': 'C',
      'The three famous Sword Styles are : ': 'A',
      'Pax Shirone is the ___ prince of Shirone.': 'D',
      'The strongest nation in the world is the...': 'A',
      'There are 7 main races in the world of Mushoku Tensei.\nThey are the "Human Race", "Demon Race", "Dragon Race", "Void Race" and what other 3 races ?' : 'C',
      "What's Eris's middle name ? (Eris ___ Greyrat)": ['B','E'],
      "Dragon God Orsted is currently the strongest living being in the world." : 'A',
      "Currently, the strongest human in the world is..." : 'B',
      "Rudeus has two little sisters, named:" : 'B',
      "The Green ore coin is the highest valued coin on the Demon Continent.\nHow many Asuran Gold Coins is one of them worth ?" : 'D',
      "Armored Dragon King, Perugius Dola is famous for...." : 'C',
      "The most dangerous continent in the world is said to be the..." : "D",
      "Why is the Teleportation Labyrinth regarded as the most dangerous dungeon in the world ?" : "A",
      "The 'Strife Zone' is..." : "C",
      "Before Zenith became an adventurer in Paul's party, she was...?" : "D",
      "The spears wielded by Supard warriors come from...?" : "C",
      "God-tier healing magic is capable of reviving even the dead." : "B",
      "Paul's adventuring party was known as '____', and they were a(n) _ tier adventuring party" : "A",
      "Ghislaine Dedoldia is also called ___ by some people." : "C",
      "Who started the First Great Human-Demon War ? " : "D",
      "Who started the Second Great Human-Demon War ? " : "A",
      "Who started the Third Great Human-Demon War ? " : "C",
      "During Laplace's War, Perugius and his six comrades became known as 'The Seven Heroes'. Which of these were not one of them ?\n(hint: think logically)" : "B",
      "Which one of the following did not take part during the final battle against Laplace during the Third Great Human-Demon War ?\n(choose the most likely answer)" : "D",
      "___ was held responsible for the Mana Calamity(Teleportation Incident) and sentenced to execution." : "D",
      "Cliff Grimoire is..." : "A",
      "Dragon God Orsted is the..." : ['B','C'],
      "Among these, which are viable ways to cross FROM the Demon Continent TO the Central Continent ?" : ['A','C','D'],
      "What is the official name for the world Rudeus was reincarnated into ?" : ['C','D'],
      "Geese(Gisu) Nukadia  belongs to the ___ race " : ['A','D'],
      "Between the following, Silent Seven Stars is most famous for :" : "A",
      "Perugius's strongest power is his ____" : "B",
      "Zanoba is a miko (blessed child). What is his gift ?" : "C",
      "Why is a/the Sacred Beast born ?" : "C",
      "Of the three Holy Millision military knight orders, which order is put in charge of stamping out heresy ?" : "C",
      "Kishirika Kishirisu possesses 12 Demon Eyes, which she may grant to anyone she chooses. Which of the following isn't one of them ?" : "A",
      "Kishirika Kishirisu possesses 12 Demon Eyes, which she may grant to anyone she chooses. Which of the following isn't one of them ?" : "D",
      "Kishirika Kishirisu offered Rudeus one of her 12 Demon Eyes. Which of the following did Rudeus choose" : "B"
    }